---
title: "R List of Functions"
author: "Patrik Widmer"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vectors

```{r cars}
# Sum up two vectors
c(10,20,30) + c(1,2,3)

#Recycle Vectors: Reuse the first element in the vector if the last element in the vector is "used"
c(10,20,30) + 1:6


# Access elements of a vector with a logical vector.
v.age <- c(15, 17, 34, 6, 101)
v.age.true <- v.age[c(FALSE,TRUE,TRUE,TRUE,FALSE)]
v.age.true 

```

## Matrices


```{r}
# create a matrices with matrix()
Mat_1 <- matrix(data = 0:5, ncol = 3) 
Mat_1


Mat_2 <- matrix(data = 10:15, ncol = 3) 
Mat_2


# sum or multiply matrices
Mat_1 + Mat_2
```

Access Matrices
Accessing elements of a matrix is also done via indexing. Two dimensions must be specified.
Matrix.name[row(s), column(s)]

```{r}

Mat_1[1,2]

#By omitting one dimension we get the entire row, respectively the entire column.
Mat_1[2, ]

Mat_1[ , 2:3]

```

## Create a data frame

```{r}
## creating a data frame
v.participant.name <- c("Max", "Tony Müller", "Andreas", "Ramona", "Nick Q.")
v.age <- c(17, 23, 45, 11, 44)
v.minor.YES <- c(TRUE, FALSE, FALSE, TRUE, FALSE)
##
d.test <- data.frame(v.participant.name, v.age, v.minor.YES)
d.test
```


## Get an overview of the data

```{r}
str(iris)

dim(iris)

ncol(iris) #

nrow(iris) #

summary(iris)

table(iris[, "Species"])


head(iris)

```


## Graphics and Plots

Scatterplot

```{r}
plot(y = iris$Sepal.Length, 
     x = iris$Sepal.Width,
     main = "Iris Sepal Width vs rates Sepal Length",
     xlab = "Sepal.Length",
     ylab = "Sepal.Width" )
```


Histogram
```{r}
hist(x = iris$Petal.Length)
hist(x = iris$Petal.Width)
```
Boxplot
```{r}
boxplot(Sepal.Length ~ Species, data = iris)
```


Plot all variable of a  dataset against each other
```{r}
pairs(iris)
pairs(swiss)

```




### Create a PDF
```{r}
## device control functions
pdf(file = "./Testing_ThePdfFunction.pdf")
plot(1:10, 1:10, main = "test")
abline(v = 5)
dev.off()
## remember...the working directory
getwd()
```









